<a href="https://colab.research.google.com/github/Kel24/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Problem 1


In [34]:
import numpy as np
A = np.array ([[1,1,1],[1,0,4],[0,0,5]])#creation of a Matrix A
print(A,"\n")
inv_A = np.linalg.inv(A) #Inverse
print(inv_A,"\n")
B = np.array([[89],[89],[95]]) #creation of a Matrix B
print(B,"\n")
X = np.linalg.inv(A).dot(B)
print("Roots of the linear equation")
print(X,"\n")
B = np.dot(A,X) #To check if the answer is correct
print("Checking")
print(B)

[[1 1 1]
 [1 0 4]
 [0 0 5]] 

[[ 0.   1.  -0.8]
 [ 1.  -1.   0.6]
 [ 0.   0.   0.2]] 

[[89]
 [89]
 [95]] 

Roots of the linear equation
[[13.]
 [57.]
 [19.]] 

Checking
[[89.]
 [89.]
 [95.]]


##Problem 2


In [33]:
import numpy as np
from scipy.linalg import solve
A = np.array ([[3,-1,1],[9,-3,3],[-12,4,-4]])#creation of a Matrix A
print(A,"\n")
B = np.array([[5],[15],[-20]]) #creation of a Matrix B
print(B,"\n")
X = solve(A,B)
print(X)

#This problem cannot be solved due to the matrix is singular, which means that there is a matrix whose determinant is 0, 
#and it is a non-invertible matrix.

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]] 

[[  5]
 [ 15]
 [-20]] 



LinAlgError: ignored

##Problem 3

In [32]:
import numpy as np
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]]) #creation of a Matrix
print(A,"\n")
w,v = np.linalg.eig(A) #Getting the eigenvalues and eigenvectors
print("The eigenvalue/s is/are:",w,"\n")
print("The right eigenvectors are:","\n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalue/s is/are: [-1.  3.  2.] 

The right eigenvectors are: 
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
