<a href="https://colab.research.google.com/github/Kel24/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Midterm Exam

##Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [2]:
import numpy as np 
A = np.zeros ((5,5)) #Creating a 5x5 matrix
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


##Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [22]:
import numpy as np 
B= np.array([[1,1,1],[0,1,1],[0,0,1]])#Creating Matrix below the principal are zero
print(B)

[[1 1 1]
 [0 1 1]
 [0 0 1]]


##Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [45]:
import numpy as np                       
D = np.array([[1,7,3],[7,4,5],[3,5,0]])   #creating an array 
print("Original Matrix")
print(D,"\n")  
print("Symmetrical Matrix")                              
E = np.transpose(D)               
print(E)  


Original Matrix
[[1 7 3]
 [7 4 5]
 [3 5 0]] 

Symmetrical Matrix
[[1 7 3]
 [7 4 5]
 [3 5 0]]


##Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [12]:
import numpy as np
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #creation of matrix C
print(C,"\n")
inv_C = np.linalg.inv(C) #to show the inverse of matrix C
print(inv_C)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]] 

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [33]:
import numpy as np
A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(A)
print(round(np.linalg.det(A))) #for the determinant of the given matrix

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5


##Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [49]:
import numpy as np
A = np.array ([[5,4,1],[10,9,4],[10,13,15]])
print(A,"\n")
inv_A = np.linalg.inv(A)
print(inv_A,"\n")
B = np.array([[3.4],[8.8],[19.2]]) #creation of a Matrix B
print(B,"\n")
X = np.linalg.inv(A).dot(B)
print("Roots of the linear equation")
print(X,"\n")
B = np.dot(A,X) #To check if the answer is correct
print(B)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]] 

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]] 

[[ 3.4]
 [ 8.8]
 [19.2]] 

Roots of the linear equation
[[0.2]
 [0.4]
 [0.8]] 

[[ 3.4]
 [ 8.8]
 [19.2]]
