<a href="https://colab.research.google.com/github/Kel24/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Practical Lab Exam 1

In [6]:
import numpy as np
A = np.array (([1,2,3],[4,5,6]))
B = np.array ((([1,2],[3,4],[5,6])))
C = np.array ((([1,2,3],[4,5,6],[7,8,9])))
D = np.array (([1,2],[3,4]))

print(A,"\n" )
print(B,"\n")
print(C,"\n")
print(D,"\n")
dot = np.dot(A,B)
print(dot,"\n")
print(D+D,"\n")
print(2*C)

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2]
 [3 4]] 

[[22 28]
 [49 64]] 

[[2 4]
 [6 8]] 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [7]:
import numpy as np
θ = np.array ([5,3,-1])


print(θ,"\n")
print("Data type:",θ.dtype )
print("Type:", type(θ))
print("Shape:", θ.shape) 
print("Dimension:",θ.ndim )

[ 5  3 -1] 

Data type: int64
Type: <class 'numpy.ndarray'>
Shape: (3,)
Dimension: 1
