<a href="https://colab.research.google.com/github/Kel24/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [30]:
#Sum of A and B
import numpy as np
A = np.array (([-5,0,],[4,1])) 
B = np.array (([6,-3,],[2,3])) 

print(A+B)



[[ 1 -3]
 [ 6  4]]


In [29]:
#Difference 1 B and A
import numpy as np
A = np.array (([-5,0,],[4,1])) 
B = np.array (([6,-3,],[2,3])) 
print(B-A)

[[11 -3]
 [-2  2]]


In [28]:
#Difference 2 of A and b
import numpy as np
A = np.array (([-5,0,],[4,1])) 
B = np.array (([6,-3,],[2,3])) 
print(A-B)

[[-11   3]
 [  2  -2]]
