<a href="https://colab.research.google.com/github/Kel24/Linear-Algebra-58019/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
A = np.array(([[4,10,8],[10,26,26],[8,26,61]])) #creation of matrix A
print(A,"\n")
inv_A = np.linalg.inv(A)
print(inv_A)




[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]] 

[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]


In [11]:
B = np.array([[44],[128],[214]])
print(B,"\n")

[[ 44]
 [128]
 [214]] 



In [14]:
C = np.dot(inv_A,B)
print(C)

[[-8.]
 [ 6.]
 [ 2.]]


##To check if the answer is correct


In [15]:
D = np.dot(A,C)
print(D)

[[ 44.]
 [128.]
 [214.]]
