<a href="https://colab.research.google.com/github/Kel24/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Representing Vectors

In [ ]:
import numpy as np

A=np.array([4,2])
B=np.array([2,-5])

print("Vector A is ", A)
print("Vector B is ", B )

Vector A is  [4 2]
Vector B is  [ 2 -5]


##Describing Vectors in Numpy


In [ ]:
import numpy as np

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])
pool.shape
pool.ndim

2

In [ ]:
U = np.array(([1,2,3],[4,5,6]))
U
U.size

6

#Space

##Vector spaces are matematical objects that abstractly capture the geometry and algebra of linear equations

###Addition of Vectors

In [ ]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [ ]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
resultant

array([1, 1, 0])

###Subtraction of Vector

In [ ]:
#You will subtract the components of addend 2 from addend 1 : addend1-addend 2
difference = addend1-addend2
difference


array([-1, -1,  0])

In [ ]:
difference2 = np.subtract(addend1,addend2)
difference2

array([-1, -1,  0])

###Scaling

In [ ]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

###Cross Product

In [ ]:
A = np.array([2,3,4])
B = np.array([1,7,1])

#Compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

[-25   2  11]


In [3]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])

#Compute the dot product of A and B

dot = np.dot(A,B)
print(dot)

23
